version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: nest-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - nest-network

  authentication: 
    build:
      context: .
      dockerfile: dockerfile
    container_name: nest-auth-service
    command: ["node", "dist/apps/authentication/main.js"]
    ports:
      - '3001:3001'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/nest-db
      - PORT=3001
      - AUTH_HOST=0.0.0.0
      - JWT_SECRET=super_segreto
    depends_on:
      - mongo
    networks:
      - nest-network

  gateway:
    build:
      context: .
      dockerfile: dockerfile
    container_name: nest-gateway
    command: ["node", "dist/apps/gateway/main.js"]
    ports:
      - '3000:3000'
    environment:
      - AUTH_HOST=authentication
      - AUTH_PORT=3001
      - JWT_SECRET=super_segreto
    depends_on:
      - authentication
    networks:
      - nest-network

volumes:
  mongo_data:

networks:
  nest-network:
    driver: bridge